config/routes.rb
AsKuery::Application.routes.draw do

  get "system/index"

  resources :votes
  resources :posts
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/askuery' => 'system#index'
  match '/system' => 'system#index'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy'
  match '/sessions/:id' => 'sessions#destroy'
  match '/profile' => 'users#show'
  match '/system/add_new_post' => 'system#add_new_post'
  match '/system/add_new_reply' => 'system#add_new_reply'
  match '/system/add_new_vote' => 'system#add_new_vote'
  match '/system/grant_admin' => 'system#grant_admin'
  match '/system/revoke_admin' => 'system#revoke_admin'
  match '/posts/:id' => 'posts#destroy'
  match '/system/delete_user' => 'system#delete_user'
  match '/system/search_results' => 'system#search_results'
  match '/system/see_all_questions' => 'system#see_all_questions'

  root :to => 'system#index'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  has_many :posts
  has_many :votes

  validates_presence_of :username

  validates_presence_of :email
  validates_presence_of :name

  validates_uniqueness_of :username
  validates_presence_of :password
  validate :password_check

  validates_format_of :email,:with => /\b[A-Z0-9._%a-z-]+@(?:[A-Z0-9a-z-]+.)+[A-Za-z]{2,4}\z/

  before_save :encrypt_password

  def encrypt_password
    if new_record?
      self.password = Digest::SHA2.hexdigest(self.password)
    end
    if self.isadmin.nil?
      self.isadmin=0
    end
  end

  def self.authenticate(user_name, password)
    user = self.find_by_username(user_name)
    if !user.nil?
      password = Digest::SHA2.hexdigest(password)
      if user.password.eql? password
        return user
      end
    end
    nil
  end

  def self.search(key)
    all(:conditions => ["lower(#{:username}) like ?", '%' + key.downcase + '%'])
  end

private
  def password_check
      if self.password.blank?
        errors.add(:password, "field can not be empty")
      end
      errors.add(:password, "can not be smaller than 6 or greater than 20 characters:"+self.password+":") if self.password.length < 6 or self.password.length > 20
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper
  # GET /users
  # GET /users.json
  def index
    if session[:id]
      @users = User.all
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @users }
      end
    else
      flash[:error] = "You will need to Sign In to view this page."
      redirect_to :controller => 'system', :action => 'index'
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show

    if session[:id]
      myposts = ""
      @from_list = params[:from_list]
      if params[:id]
        @user = User.find(params[:id])
      elsif session[:id]
        @user = User.find(session[:id])
      else
        flash[:error] = "You will need to Sign In to view this page."
        redirect_to :controller => 'system', :action => 'index'
      end

      if @user
        @numofposts = 0
        myposts = get_my_posts(@user)
        if myposts.nil? == false && myposts.instance_of?(Array)
          @numofposts = myposts.length
        end

        respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @user }
        end
      else
        flash[:error] = "The user does not exist"
        redirect_to :controller => 'system', :action => 'index'
      end
    else
      flash[:error] = "You will need to Sign In to view this page."
      redirect_to :controller => 'system', :action => 'index'
    end

  end

  # GET /users/new
  # GET /users/new.json
  def new
    if params[:create_user] == '1' or session[:id]
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    else
      flash[:error] = "You will need to Sign In to view this page."
      redirect_to :controller => 'system', :action => 'index'
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end

private
  def get_my_posts(user)
     myposts = Post.find_all_by_user_id(user.id)
     myposts
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def get_number_of_posts(u)
    Post.get_user_post_count(u)
  end

  def get_number_of_votes_for(u)
    Post.get_num_votes_for(u)
  end

  def get_number_of_votes_by(u)
    Vote.get_num_votes_by(u)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <% if session[:id] and session[:isadmin] == 1 %>
      <div class="field">
          <br />
          <%= f.label "Check to grant Admin Rights" %>
          <%= f.check_box :isadmin %>
    </div>
  <% end %>


  <div class="actions">
    <br />
    <div class="form-button-other-panel">
      <% if session[:id] and session[:isadmin] == 1 %>
        <%= f.submit "Create User", :from_list => '1', :class => 'form-button-other'  %>
      <% else %>
        <%= f.submit "Sign Up", :class => 'form-button-other' %>
      <% end %>
    </div>
    <hr>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td class="td-login"><%= link_to user.username, :controller => 'users', :action => 'show', :id => user.id, :from_list => '1' %></td>
  <td class="td-uname"><%= user.name %></td>
  <td class="td-email"><%= user.email %></td>
  <% if session[:isadmin] == 1  %>
    <td class="td-posts"><%= get_number_of_posts(user.id) %></td>
    <td class="td-votes-for"><%= get_number_of_votes_for(user.id) %></td>
    <td class="td-votes-by"><%= get_number_of_votes_by(user.id) %></td>
  <% end %>

  <% if session[:isadmin] == 1 and session[:id] != user.id and user.username != 'admin-admin' %>

    <td class="td-delete"><%= button_to 'Delete This User',  {:controller => 'system', :action => 'delete_user', :user_id => user.id, :listing => '1'}, :class => 'form-button-other' %></td>
    <% if user.isadmin == 0 %>
      <td class="td-admin"><%= button_to 'Grant Admin',  {:controller => 'system', :action => 'grant_admin', :user_id => user.id}, :class => 'form-button-other' %></td>
    <% else %>
      <td class="td-admin"><%= button_to 'Revoke Admin',  {:controller => 'system', :action => 'revoke_admin', :user_id => user.id}, :class => 'form-button-other' %></td>
    <% end %>
  <% else %>
  <% end %>
</tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div>
  <br />
</div>
<div class="title">
  Users
</div>

<div class="user-list-container">
  <% if session[:id] %>
    <table>
      <tr>
        <th>Username</th>
        <th>Name</th>
        <th>Email</th>
        <% if session[:isadmin] == 1 %>
          <th>Posts</th>
          <th>Votes for</th>
          <th>Votes By</th>
          <th></th>
          <th></th>
        <% end %>
      </tr>
      <%= render @users %>
    </table>
  <% else %>
    You need to login to view this page! <%= link_to "Sign In", :controller => 'sessions', :action => 'new' %>
  <% end %>
</div>

<div>
  <br />
  <hr>
  <%= link_to "Go to homepage", :controller => 'system', :action => 'index' %>
</div>

app/views/users/new.html.erb
<div class="title">
  <br />
  <% if session[:id] and session[:isadmin] == 1 %>
    Create User
  <% else %>
    New User Sign Up
  <% end %>
  <br />
  <hr>
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="title">
 <br />
 User Profile
  <hr />
</div>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<% if @numofposts == 0 %>
    <p>
      <b> <%= @user.username %> has not posted any questions yet.</b>
    </p>
<% else %>
    <p>
      <b>Number of Posts by <%= @user.username %>:</b>
      <%= @numofposts %>
    </p>
<% end %>

<% if @user.isadmin == 1 %>
<p>
  <b> <%= @user.username %> has Admin Functionality.</b>
</p>
<% end %>

<% if session[:isadmin] == 1 and session[:id] != @user.id and @user.username != 'admin-admin' %>
  <div class="form-button-other-panel">
    <% if @user.isadmin == 0 %>
      <%= button_to 'Grant Admin',  {:controller => 'system', :action => 'grant_admin', :user_id => @user.id}, :class => 'form-button-other' %> <br />
    <% else %>
      <%= button_to 'Revoke Admin',  {:controller => 'system', :action => 'revoke_admin', :user_id => @user.id}, :class => 'form-button-other' %> <br />
    <% end %>
  </div>
  <div class="form-button-other-panel">
    <%= button_to 'Delete This User',  {:controller => 'system', :action => 'delete_user', :user_id => @user.id, :listing => @from_list}, :class => 'form-button-other'  %> <br />
  </div>
<% end %>

<hr />
<%= link_to 'Go To Homepage',  :controller => 'system', :action => 'index' %>